### ISSUE TITLE
Return objects not dictionaries

### ISSUE THREAD

**Issue by joshuaduffy** [joshuaduffy/dota2api#21]
See the object branch for details in what this will achieve.

This is potentially going to cause a lot of backwards compatibility issues and would be v2.0 of the API wrapper.

Things to include: Images (items, heroes) any other information (hero stat gain etc)

Everything will be an object. Times/Dates, Players etc etc.

Only the response will change. It will be called/initialised in the same manner.

**Comment by evaldobratti** [comment]
There is a problem with the response of get live league games.
http://dev.dota2.com/showthread.php?t=156783

I tried to use a customized JSONDecoder, however, it didn't work as expected

I couldn't find a way to deal with this error
