### ISSUE TITLE
GetPlayerSummaries does not work if parameter is a list

### ISSUE THREAD

**Issue by evaldobratti** [joshuaduffy/dota2api#23]

**Comment by joshuaduffy** [comment]
Hey,

I start a new job in a couple of weeks so I am wanting to take a look at this and the objects when I can.

Thanks,
Josh

**Comment by evaldobratti** [comment]
No problem, I've done some work on branch 'object_response' that I've been using in a personal project. Can you take a look?

**Comment by joshuaduffy** [comment]
Ooh nice :) I'll have a look this week!

**Comment by Undingable** [comment]
Hey, I found GetPlayerSummaries just gave me output like this: {u'players': []}. Is this a new bug or I did not use the function correctly?

**Comment by evaldobratti** [comment]
This is the return if no accounts matches the parameters.

Are you converting the accounts ids to 64b before using get_player_summaries?

**Comment by Undingable** [comment]
encoded = base64.b64encode(<my steam id in string>)
api.get_player_summaries(steamids=encoded)

that's what I did.

**Comment by evaldobratti** [comment]
There is a converter in the development version

def convert_to_64_bit(number):
    return number + 76561197960265728

can you check if the results are the same?

**Comment by Undingable** [comment]
oh, I thought 64b = base64, lol my bad. thanks buddy, glhf.

**Comment by joshuaduffy** [comment]
Closing due to the latest commit into `master`.

See the documentation [here](http://dota2api.readthedocs.org/en/latest/reference.html#dota2api.Initialise.get_player_summaries) on how to use `get_player_summaries`
