### ISSUE TITLE
Missing leaver.json from package_data in setup

### ISSUE THREAD

**Issue by m-vd** [joshuaduffy/dota2api#29]
The dev version fails to import with the following error message:

FileNotFoundError: [Errno 2] No such file or directory: 'lib/python3.4/site-packages/dota2api/ref/leaver.json'

This is because it is missing in package_data in the setup.py

**Comment by joshuaduffy** [comment]
Thank you for this, seems like we need to update the Manifest. I will get this updated today and test.

**Comment by joshuaduffy** [comment]
Fixed in `dev` - master is fine as we've not merged down the leaver file.

Thanks for the report and Python 3 changes!
