### ISSUE TITLE
Python 3 - Change urllib.urlencode to urllib.parse.urlencode

### ISSUE THREAD

**Issue by m-vd** [joshuaduffy/dota2api#31]
In python 3 urlencode is now under the urllib.parse module. __init__.py needs to use this.

**Comment by joshuaduffy** [comment]
Thank you, I am planning to perform a migration to Python 3 soon. Currently only testing against 2.6/2.7.

**Comment by joshuaduffy** [comment]
Just pushed Python 3 support to main, will be updating PyPi distro's soon.
