### ISSUE TITLE
dota2api import failing

### ISSUE THREAD

**Issue by arachnotron** [joshuaduffy/dota2api#32]
A little rusty on Python, not sure how to debug. I installed from pip and it seems that the src module isn't initializing correctly.

[IDLE output]
>>> import dota2api
Traceback (most recent call last):
  File "<pyshell#2>", line 1, in <module>
    import dota2api
  File "G:\Python\Python35\lib\site-packages\dota2api\\\__init__.py", line 15, in <module>
    from src import urls, exceptions, response, parse
ImportError: No module named 'src'

"G:\Python\Python35\lib\site-packages\dota2api\src\\\__init__.py" exists so I'm not sure why the module isn't being recognized.

Is pip currently up to date with this repo?

**Comment by joshuaduffy** [comment]
Thank you for the bug report, we only support Python 2.7 for the moment.

The reason it is failing is due to the way imports are handled differently in Python 3. We will support Py3 soon!

**Comment by arachnotron** [comment]
Solid, thanks for the update.
