### ISSUE TITLE
Average MMR

### ISSUE THREAD

**Issue by xmindfirex** [joshuaduffy/dota2api#36]
With Average MMR showing in game under the watch tab, can that be pulled via the API when getting match details?

**Comment by evaldobratti** [comment]
As far as I know, there is no information about MMR in match details service.
You can see which bracket the match is through match history, requesting with 'skill' parameter set to 1 (normal), 2 (high) or 3 (very high).

You can get more information about details match [here](https://wiki.teamfortress.com/wiki/WebAPI/GetMatchDetails) and match history [here](https://wiki.teamfortress.com/wiki/WebAPI/GetMatchHistory)
