### ISSUE TITLE
Is there a mistake in dota2api/ref/abilities.json ?

### ISSUE THREAD

**Issue by banixc** [joshuaduffy/dota2api#37]
at line 1997

    1995        {
    1996            "name": "wisp_spirits_in",
    1997            "id": "wisp_spirits_out"
    1998        },

should id be a number instead of a string?

**Comment by joshuaduffy** [comment]
Hey,

Thank you for your report. The files come from valve (via the `get_heroes` call) I will check the source files from valve and if this is still the case, issue a fix on our end.

Thanks,
Josh
