### ISSUE TITLE
cant retrieve more match history

### ISSUE THREAD

**Issue by IamAppppp** [joshuaduffy/dota2api#38]
i tried to retrieve more, or all, match history, but the parameter 'matches_requested' seems dont work.
it keep returning num_results:100
my code is like: matches = api.get_match_history(xxxxxx, matches_requested)
is there anything wrong with my code?

**Comment by IamAppppp** [comment]
seems its limited by valve

**Comment by evaldobratti** [comment]
You can fetch matches with account_id, hero_id and start_at_match_id setted, so you will get at least 500 matches for each hero from that account.
