### ISSUE TITLE
Improve the tests

### ISSUE THREAD

**Issue by joshuaduffy** [joshuaduffy/dota2api#4]

**Comment by evaldobratti** [comment]
I'll start to work on test of the other parts and readability now.

**Comment by joshuaduffy** [comment]
We are at 88% code coverage, which is very good! I'm hoping the object branch doesn't cause too many issues with out existing tests, but I will amend before pushing to master (which is a long way away!)

**Comment by joshuaduffy** [comment]
Probably will close this once I look at the new pull requests tests
