### ISSUE TITLE
Issue when installing to an environment without requests installed

### ISSUE THREAD

**Issue by joshuaduffy** [joshuaduffy/dota2api#45]
Thought I fixed this one... whoops.

`λ pip install dota2api
Collecting dota2api
  Using cached dota2api-1.3.1.tar.gz
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "C:\Users\[USER]\AppData\Local\Temp\pip-build-bv98v1q4\dota2api\setup.py", line 7, in <module>
        import dota2api
      File "c:\users\[USER]\appdata\local\temp\pip-build-bv98v1q4\dota2api\dota2api\__init__.py", line 19, in <module>
        import requests
    ImportError: No module named 'requests'`

**Comment by evaldobratti** [comment]
The problem here is setup.py importing dota2api, and this one depends on 'requests'. 
I remember fixing this in some branch :(

**Comment by xrisk** [comment]
Guys, I can't install this via `requirements.txt` on heroku :( Any fix?

**Comment by joshuaduffy** [comment]
What output do you get?

Thanks,
Josh

**Comment by xrisk** [comment]
```
-----> Python app detected
-----> Installing python-3.5.2
     $ pip install -r requirements.txt
       Collecting aiohttp==0.21.6 (from -r requirements.txt (line 1))
         Downloading aiohttp-0.21.6.tar.gz (528kB)
       Collecting chardet==2.3.0 (from -r requirements.txt (line 2))
         Downloading chardet-2.3.0.tar.gz (164kB)
       Collecting click==6.6 (from -r requirements.txt (line 3))
         Downloading click-6.6.tar.gz (283kB)
       Collecting discord.py==0.11.0 (from -r requirements.txt (line 4))
         Downloading discord.py-0.11.0.zip (436kB)
       Collecting dota2api==1.3.1 (from -r requirements.txt (line 5))
         Downloading dota2api-1.3.1.tar.gz
           Complete output from command python setup.py egg_info:
           Traceback (most recent call last):
             File "<string>", line 1, in <module>
             File "/tmp/pip-build-71npjk5g/dota2api/setup.py", line 7, in <module>
               import dota2api
             File "/tmp/pip-build-71npjk5g/dota2api/dota2api/__init__.py", line 19, in <module>
               import requests
           ImportError: No module named 'requests'
           ----------------------------------------
       Command "python setup.py egg_info" failed with error code 1 in /tmp/pip-build-71npjk5g/dota2api/
 !     Push rejected, failed to compile Python app.
 !     Push failed
``` 

Mind I'm running this on Heroku so there's no way to install requests "separately" other than writing a custom buildpack. 

What I did do, however, is fork out your repo [here](https://github.com/xrisk/dota2api) and remove the install dependency for requests.

BTW, nice work on this lib :)

**Comment by joshuaduffy** [comment]
I've put a new build up on here, I'll release it to PyPi and that should fix it for you.

Thanks,
Josh

**Comment by joshuaduffy** [comment]
It's not going to work just yet... I'm on it though,

**Comment by joshuaduffy** [comment]
FIxed, and on PyPi
