### ISSUE TITLE
No Underlord!

### ISSUE THREAD

**Issue by x89** [joshuaduffy/dota2api#48]
Missing from `ref/heroes.json` and `ref/abilities.json` I believe!

**Comment by joshuaduffy** [comment]
I've updated the `heroes`,

**Comment by x89** [comment]
Thanks 😊

**Comment by joshuaduffy** [comment]
I still need to get the ability ID's though!

**Comment by x89** [comment]
Oh shit! Closed too soon! 😉

**Comment by Jammizzle** [comment]
Was this accomplished?

**Comment by ikcam** [comment]
@Jammizzle [yes! ](https://github.com/joshuaduffy/dota2api/blob/master/dota2api/ref/heroes.json#L1005)
