### ISSUE TITLE
get more matches from `api.get_match_history()`?

### ISSUE THREAD

**Issue by xunlao** [joshuaduffy/dota2api#52]
on my machine, the `api.get_match_history()['total_results']` returns `500` which is the default (I think)

but when I try to get more matches with `api.get_match_history(matches_requested=5000)['total_results']` it still returns `500`

So does `matches_requested` parameter in `api.get_match_history()` not working? Or should I use some other parameters?

**Comment by evaldobratti** [comment]
You can't get more than 500 matches through get_match_history, it's limited by valve api.
One approach you can do is alternate hero_id, like, requesting with account_id, hero_id and start_at_match_id (none if first request), values assigned, this way you can get at least 500 matches of each hero from that account_id.

**Comment by xunlao** [comment]
Thanks, I will try your advice to work it around!
