### ISSUE TITLE
Get_heroes()

### ISSUE THREAD

**Issue by zachkont** [joshuaduffy/dota2api#53]
using the get_heroes() function I get a "not defined" error. I have installed the package with pip and used get_match_details() successfully. What am I missing here?

**Comment by joshuaduffy** [comment]
Hi, thanks for the report, do you have some example code and the full stacktrace/output?

**Comment by zachkont** [comment]
It also happens just using the interpreter:
>>>import dota2api
>>>get_heroes()
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
NameError: name 'get_heroes' is not defined

**Comment by joshuaduffy** [comment]
You need to call those methods on the api object as described [here](http://dota2api.readthedocs.io/en/latest/tutorial.html#tutorial)

Thanks,
Josh

**Comment by zachkont** [comment]
Yeap, that's what I was missing. Thanks!
