### ISSUE TITLE
how get realtime details for match?

### ISSUE THREAD

**Issue by SanteR1** [joshuaduffy/dota2api#55]
Or how it is possible to obtain information about pick heroes at the beginning of the match?

**Comment by evaldobratti** [comment]
There are only 2 endpoints that show realtime info

- [get_top_live_games](http://dota2api.readthedocs.io/en/latest/responses.html#get-top-live-games)
- [get_live_league_games](http://dota2api.readthedocs.io/en/latest/responses.html#get-live-league-games)

though, I'm not sure about how these endpoints behave in the pick phase.

**Comment by SanteR1** [comment]
@evaldobratti, hi! Your two methods will work for my match of a public game?
I found here a method and judging by the description it is suitable for real time of games, but it doesn't return result for my match.

- [get_match_details()](http://dota2api.readthedocs.io/en/latest/responses.html#get-match-details)

> For dynamic values such as kills or gold, if the match is live, then the value is current as of the API call. For matches that have finished, these values are simply the value at the end of the match for the player.

**Comment by evaldobratti** [comment]
Those 2 endpoints I mentionated before will only work if you are playing a league or your matches have high mmr (problably top matches that are shown in 'watch' tab in the client).

I'm not sure if `get_match_details` return live data, cus, like others endpoints, like `get_match_history` or `get_match_history_by_seq_num` only show finished matches.

I'll check this and update the docs if necessary, but, afaik, `get_top_live_games` and `get_live_league_games` are the only endpoints with live data.
