### ISSUE TITLE
Ho to get a match from particular date?

### ISSUE THREAD

**Issue by ssrebelious** [joshuaduffy/dota2api#58]
I try to get [any] match from a particular date with `get_match_history()`, but I get matches that were played the day I run the query. I suspect that I miss something obvious... again ;-)

```python
import time
from datetime import datetime, date

def timestamp_to_human_time(timestamp):
    human_time = datetime.fromtimestamp(timestamp).strftime('%Y-%m-%d %H:%M:%S %Z')
    return human_time

date_in_seconds = time.mktime(date(2016, 12, 20).timetuple())

matches = api.get_match_history(skill=3, matches_requested=1,
                                #date_min=date_in_seconds,
                                date_max=date_in_seconds
                                )
print(matches.url)
for m in matches['matches']:
    print(m['match_id'], '||', timestamp_to_human_time(m['start_time']))
``` 
This returns:

```
http://api.steampowered.com/IDOTA2Match_570/GetMatchHistory/v001/?matches_requested=1&account_id=None&skill=3&format=json&date_max=1482181200&key=SECRET&language=en_us
2911705662 || 2017-01-13 00:29:54 
```

**Comment by joshuaduffy** [comment]
I believe the date parameter has been broken for a very long time on the official API. It seems like they're removed it.

References: https://www.reddit.com/r/DotA2/comments/2440gk/the_dota_2_web_api_is_still_broken/ http://dev.dota2.com/showthread.php?t=151068 http://dev.dota2.com/showthread.php?t=125530&page=5

**Comment by ssrebelious** [comment]
@joshuaduffy should these deprecated/broken parameters be removed from `dota2api` documentation, or at least be marked as "broken"?

**Comment by joshuaduffy** [comment]
I will remove it from the documentation, if it ever becomes available, or any keywords get added it is possible to pass it as a keyword argument and it gets added to the query string automatically.
