### ISSUE TITLE
Get_match_History() retrieval limit.

### ISSUE THREAD

**Issue by counterpig** [joshuaduffy/dota2api#60]
I was under the impression that each call of Get_match_history limits the user to 500 results but I don't seem to be able to get more than 100 matches returned no matter the number I put in matches_requested when making the call.

Is this intentional? Is it a decision by you or has valve decreased the maximum number of matches you can get per call?

**Comment by evaldobratti** [comment]
AFAIK, GetMatchHistory endpoint never returned more than 100 matches, it does'n matter if you request more than it.

It's valve decision, we just return the result given by the valve api.
