### ISSUE TITLE
start_at_match_id broken when using get_match_history.

### ISSUE THREAD

**Issue by counterpig** [joshuaduffy/dota2api#61]
I am trying to get a sequence of matches using get match data and the following line.

matches = api.get_match_history(game_mode=2, skill=3, min_players=10, matches_requested=100, start_at_match_id = 3001179359)

The result I get is a status of 1 implying it has functioned correctly but an empty match list. Is this parameter broken? If so how would I go about retrieving a list of matches? would I have to use the get_match_history_by_sequence_number and manually filter the data?

**Comment by viking-sudo-rm** [comment]
I am also having problems using get_match_history. When I attempt to filter by game_mode, it doesnt work:

matchHistory = api.get_match_history(game_mode=2, skill=3, min_players=10)
print matchHistory
for match in matchHistory["matches"]:
	print api.get_match_details(match["match_id"])["game_mode"]

**Comment by evaldobratti** [comment]
There is nothing much the wrapper can do about it, unfortunetaly it's valve api that brings wrongs results/ignore parameters.
There is a [list](http://dev.dota2.com/showthread.php?t=57331) here with some known bugs.
